spring:
  # 配置数据源
  datasource:
    url: jdbc:mysql://10.201.6.7:3306/demo?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: demo
    password: demo

mybatis-plus:
  # 配置mapper
  mapper-locations: classpath:/mapper/mybatisplusdemo/*.xml
  # 全局策略配置
  global-config:
    db-config:
      # 主键自增
      id-type: ASSIGN_ID
      # 逻辑删除
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)
      # 表前缀
      #table-prefix: mp_

  # 查看执行的sql语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # map-underscore-to-camel-case: false

server:
  port: 9007
